### ISSUE TITLE
Corda Network throws NullPointerException after interoperation data request

### ISSUE THREAD

**Issue by sandeepnRES** [hyperledger-labs/weaver-dlt-interoperability#9]
Run an interoperation flow where either Fabric network requests the Corda network for data. The flow succeeds, with the proof getting verificed back in the Fabric network. But the Corda network reports an exception (though it doesn't crash).

Interoperation command:
```
./bin/fabric-cli interop --local-network=network1 --sign=true --requesting-org=Org1MSP localhost:9081/Corda_Network/localhost:10006#com.cordaSimpleApplication.flow.GetStateByKey:H --debug=true
```

Exception thrown by the Corda network:
```
com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
policy_ (common.query.QueryOuterClass$Query)
query (com.cordaInteropApp.flows.HandleExternalRequest)
logic (net.corda.node.services.statemachine.FlowStateMachineImpl)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
        at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:145)
        at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:782)
        at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObjectOrNull(ReplaceableObjectKryo.java:107)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132)
        at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:145)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
        at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObject(ReplaceableObjectKryo.java:92)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
        at co.paralleluniverse.fibers.Fiber$FiberSerializer.read(Fiber.java:2156)
        at co.paralleluniverse.fibers.Fiber$FiberSerializer.read(Fiber.java:2086)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
        at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readClassAndObject(ReplaceableObjectKryo.java:112)
        at net.corda.node.serialization.kryo.KryoCheckpointSerializer$deserialize$1$1.invoke(KryoCheckpointSerializer.kt:83)
        at net.corda.node.serialization.kryo.KryoCheckpointSerializer$deserialize$1$1.invoke(KryoCheckpointSerializer.kt:33)
        at net.corda.node.serialization.kryo.KryoStreams.kryoInput(KryoStreams.kt:20)
        at net.corda.node.serialization.kryo.KryoCheckpointSerializer$deserialize$1.invoke(KryoCheckpointSerializer.kt:72)
        at net.corda.node.serialization.kryo.KryoCheckpointSerializer$deserialize$1.invoke(KryoCheckpointSerializer.kt:33)
        at net.corda.node.serialization.kryo.KryoCheckpointSerializer$kryo$1.execute(KryoCheckpointSerializer.kt:61)
        at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:58)
        at net.corda.node.serialization.kryo.KryoCheckpointSerializer.kryo(KryoCheckpointSerializer.kt:57)
        at net.corda.node.serialization.kryo.KryoCheckpointSerializer.deserialize(KryoCheckpointSerializer.kt:71)
        at net.corda.node.services.statemachine.interceptors.FiberDeserializationChecker$start$2.invoke(FiberDeserializationCheckingInterceptor.kt:101)
        at net.corda.node.services.statemachine.interceptors.FiberDeserializationChecker$start$2.invoke(FiberDeserializationCheckingInterceptor.kt:51)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: java.lang.NullPointerException
        at com.google.protobuf.UnmodifiableLazyStringList.size(UnmodifiableLazyStringList.java:68)
        at java.util.AbstractList.add(AbstractList.java:108)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
        at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObject(ReplaceableObjectKryo.java:92)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
        ... 25 more
[ERROR] 20:18:29+0000 [FiberDeserializationChecker] interceptors.FiberDeserializationChecker. - Encountered unrestorable checkpoint! [errorCode=tqq5sj, moreInformationAt=https://errors.corda.net/OS/4.4/tqq5sj]
```

**Comment by VRamakrishna** [comment]
This is a known issue in Corda, tracked in https://r3-cev.atlassian.net/browse/CORDA-3717.

In a nutshell, if the constructors of a class are `private` and hence the Kryo framework has no visibility into them, it can't serialize an object instance of that class.

The alternative is registering a custom serializer for the class in Corda, and such a feature was created and outlined [here](https://docs.corda.net/docs/corda-os/4.8/cordapp-custom-serializers.html).

Now it seems our Interop CorDapp does indeed implement and export a custom serializer for the `Query` class [here](https://github.com/hyperledger-labs/weaver-dlt-interoperability/blob/main/core/network/corda-interop-app/interop-workflows/src/main/kotlin/com/weaver/corda/app/interop/flows/customSerializers/QuerySerializer.kt). So  I'm not sure exactly why we are still getting a `NullPointerException`. I tried checking and initializing the `policy` field in the `toProxy` function as follows:
```
policy = if (obj.policyList != null) obj.policyList else listOf()
```
But this doesn't work either.

@sanvenDev Let me know if you can think of anything.

**Comment by sanvenDev** [comment]
Was this issue fixed? I no longer see such exception in corda nodes logs.

**Comment by VRamakrishna** [comment]
I think we still saw this error as long as we were using the Corda `4.8.4` image version. I can't recall seeing it lately.

**Comment by sanvenDev** [comment]
Okay I tested it today, and in didn't see it in weaver testnet (using 4.8), may be you can check in Trade demo, if you don't see it there either, we can close this issue.

**Comment by VRamakrishna** [comment]
OK, let me close it since we haven't seen this issue occur since the Corda version change.
